modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "LGPL-3.0-only"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''${mod_description}'''
authors = "${mod_authors}"
displayURL = "https://modrinth.com/mod/marieslib"
logoFile = "MariesLib_icon.png"

[[mixins]]
config = "marieslib.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "cloth_config"
type = "optional"
versionRange = "[15.0.0,)"
ordering = "NONE"
side = "CLIENT"
